### ISSUE TITLE
support websockets

### ISSUE THREAD

**Issue by unixfox** [suyashkumar/ssl-proxy#15]
I would love to see a support for websockets.

**Comment by suyashkumar** [comment]
Great thought, I will need to look into WSS a bit more. Since WSS is just the websockets protocol over TLS (also on port 443 by default), I think the TLS handshake part should be the same. I'll need to look into the other differences specific to the websockets protocol.

Would you be interested in contributing a patch for this?

**Comment by fenio** [comment]
I guess Home-Assistant doesn't work with this proxy because of lack of websockets support.
I wasn't able to get it working with it.

**Comment by lindell** [comment]
This seems to have been fixed in the golang reverse proxy since Golang 1.12
I did just compile ssl-proxy with 1.13 and everything seems to work :) 
https://github.com/golang/go/issues/26937
https://go-review.googlesource.com/c/go/+/146437/

**Comment by unixfox** [comment]
Should I close this issue then?

**Comment by lindell** [comment]
I'm not sure which version the latest release is compiled with since I had to compile it myself (running on ARM)
https://github.com/suyashkumar/ssl-proxy/releases
There might be a need to recompile and release.

**Comment by suyashkumar** [comment]
@lindell thanks for the tip! I went ahead and re-released the prebuilt binaries built using Go 1.13.3 here: https://github.com/suyashkumar/ssl-proxy/releases so all should be good on the websockets front!
