### ISSUE TITLE
cannot find package "golang.org/x/crypto/acme/autocert"

### ISSUE THREAD

**Issue by schildbach** [suyashkumar/ssl-proxy#25]
When building the Docker image from 83836bc45dce88f6a0474f8b0853419ade787af2, I get:

```
$ docker build -t my/ssl-proxy .
[...]
Step 6/6 : RUN make
 ---> Running in 0cc1b0b6fa3d
go mod download
warning: pattern "all" matched no module dependencies
go build -o ssl-proxy
main.go:16:2: cannot find package "golang.org/x/crypto/acme/autocert" in any of:
        /usr/local/go/src/golang.org/x/crypto/acme/autocert (from $GOROOT)
        /go/src/golang.org/x/crypto/acme/autocert (from $GOPATH)
make: *** [Makefile:6: build] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```

This is on Ubuntu 18.04.4, using Docker version 18.09.7, build 2d0083d (from the Ubuntu repository).

**Comment by schildbach** [comment]
Same problem on the v0.2.5 tag.

**Comment by suyashkumar** [comment]
Hi there @schildbach thanks so much for raising this issue! It appears this is because the Docker image used Go 1.12. After upgrading to Go 1.13, everything seems good to go. #26 should address this, and I'll look into GitHub actions that can test the Docker build as well if we will continue to maintain that. Let me know if you have any further trouble! 

Thank you!
