### ISSUE TITLE
Generation of redirect URL goes to https://0.0.0.0

### ISSUE THREAD

**Issue by amenk** [suyashkumar/ssl-proxy#27]
I am using that docker container https://github.com/AddisMap/ssl-proxy-docker/tree/patches with

    -from 0.0.0.0:443 -redirectHTTP -domain example.com

Now it would redirect to https://0.0.0.0:443

   -from example.com:443

would not work, because it cannot bind to the address (maybe because it's in the docker container)

Can't we just use the `-domain` value for redirection?

**Comment by suyashkumar** [comment]
Hi there! Apologies for the delay (lots going on lately).

Yeah, I think we should improve the -redirectHTTP logic here. If a domain is specified, we should use that value during redirection. I'm thinking this is okay because if ssl-proxy is up, then that means the ACME challenge has been passed for your domain. 

If a `-domain` is not specified, I think we should probably continue to use the base URL. In this case if its a `0.0.0.0` type address, then it'll redirect to localhost (which would mostly be useful just for local development). I think the user may be able to supply the public IP address of the server as well here if they wanted.

**Comment by amenk** [comment]
@suyashkumar  Awesome - thanks! can you tag a new release and I will test it :)

**Comment by suyashkumar** [comment]
Yep! Prebuilt binaries are now available under releases, and you can always grab the latest prebuilt binaries to your machine using:
```
wget -qO- "https://getbin.io/suyashkumar/ssl-proxy" | tar xvz 
```

Of course you can always build from source--the new tag is v0.2.6. Let me know how that works out for you, and if you have any other questions, suggestions, or contributions! Thank you again for filing the issue! :)

**Comment by amenk** [comment]
sorry for the late response. I can confirm it works well. Just updated https://github.com/AddisMap/ssl-proxy-docker/tree/patches

Thank you very much.

**Comment by suyashkumar** [comment]
@amenk awesome, glad to hear it. No problem :).

**Comment by josephsmendoza** [comment]
I'm having this issue as well with `-from 0.0.0.0:443 -to 127.0.0.1:8080 -redirectHTTP` when trying to reach a site on my internal network.

**Comment by josephsmendoza** [comment]
Forgot to mention I'm accessing this site by hostname, so using `-to hostname:8080` is enough to make the redirect work.
